import { Nav, Footer } from "@/components/site-shell";

const scoreRows = [["ICP fit","92"],["Recruitment demand","86"],["Timing","77"],["Evidence confidence","81"],["Total","84"]];
const vacancyRows = [["Senior Data Engineer","Jakarta","6 July 2026","30+ days","Persistent"],["Analytics Engineer","Jakarta","10 July 2026","12 days","New"],["ML Engineer","Remote, Indonesia","10 July 2026","12 days","Specialist"]];
const sources = [
  {type:"Official careers page",detail:"Vacancy titles and locations",first:"6 July 2026",checked:"20 July 2026"},
  {type:"Public applicant-tracking page",detail:"Posting status and role descriptions",first:"10 July 2026",checked:"20 July 2026"},
  {type:"Company announcement",detail:"Product-expansion context",first:"16 July 2026",checked:"20 July 2026"},
];
const stakeholders = [
  {order:1,role:"Head of Talent Acquisition",reason:"Owns recruitment capacity and agency relationships.",objective:"Understand internal recruitment capacity and external-agency usage."},
  {order:2,role:"Data Engineering Director",reason:"Closest to the specialist roles and likely urgency.",objective:"Validate role requirements, talent scarcity, and urgency."},
  {order:3,role:"VP Engineering",reason:"Can connect hiring delays to delivery priorities.",objective:"Understand whether open roles are affecting delivery timelines."},
  {order:4,role:"Head of People",reason:"May sponsor workforce planning and approvals.",objective:"Explore workforce-planning priorities and the approval process."},
];

export default function Sample() {
  return <><Nav/><main>
    <section><div className="container"><div className="eyebrow">Fictional demonstration</div><h1>NusantaraPay opportunity brief</h1><p className="lead">Financial technology · Indonesia · 501–1,000 employees</p><div className="grid3"><div className="card"><div className="metric">84/100</div><b>Opportunity score</b></div><div className="card"><div className="metric">Contact now</div><b>Recommendation</b></div><div className="card"><div className="metric">High</div><b>Evidence confidence</b></div></div></div></section>
    <section className="tint"><div className="container"><div className="pattern-banner"><div><span className="tag">Pattern detected</span><h2>Specialist hiring bottleneck</h2><p>Several related specialist vacancies, including repeated or long-open positions.</p></div><div><span className="tag">Evidence confidence</span><strong>High</strong><p>Multiple fictional source types support the observed hiring pattern.</p></div></div><div className="signal-stack-detail"><h3>Signal stack</h3><div>{["Seven technology vacancies","Three related data roles","Two persistent postings","Recent product-expansion context","Strong agency sector and role-family match"].map(signal=><span key={signal}>✓ {signal}</span>)}</div></div></div></section>
    <section><div className="container grid2"><div><h2>Why it fits</h2><ul className="list"><li>Geographic match: Indonesia</li><li>Industry match: financial technology</li><li>Role-family match: data engineering</li><li>Commercial fit: multiple specialist vacancies</li><li>Company-size fit: mid-market enterprise</li></ul></div><div className="card"><h3>Opportunity hypothesis</h3><p>NusantaraPay may need external recruitment support for its data-engineering expansion because multiple related specialist positions are being recruited simultaneously and some have remained visible for an extended period.</p><div className="warning">This is an inference based on fictional public evidence. It is not confirmed internal information.</div></div></div></section>
    <section><div className="container grid2 score-section"><div><p className="eyebrow"><span/> Explainable scoring</p><h2>Why the score is 84</h2><p className="lead">Each dimension is scored separately so an agency can inspect the reasoning—not just the recommendation.</p><div className="score-caveat"><strong>What reduced the score</strong><p>Expansion evidence is indirect, and no external-agency usage has been confirmed.</p></div></div><div className="card"><table><thead><tr><th>Dimension</th><th>Score</th></tr></thead><tbody>{scoreRows.map(([dimension,score])=><tr className={dimension==="Total"?"total-row":""} key={dimension}><td>{dimension}</td><td><strong>{score}</strong></td></tr>)}</tbody></table></div></div></section>
    <section className="tint"><div className="container"><p className="eyebrow"><span/> Vacancy evidence</p><h2>Jobs behind the signal</h2><p className="lead">The brief keeps the underlying roles visible so persistence, timing, and specialization can be checked.</p><div className="table-scroll"><table><thead><tr><th>Role</th><th>Location</th><th>First observed</th><th>Age</th><th>Signal</th></tr></thead><tbody>{vacancyRows.map(row=><tr key={row[0]}>{row.map(cell=><td key={cell}>{cell}</td>)}</tr>)}</tbody></table></div></div></section>
    <section><div className="container"><p className="eyebrow"><span/> Evidence provenance</p><h2>What a source record looks like</h2><p className="lead">These disabled records demonstrate the format. They do not link to real companies or sources.</p><div className="source-grid">{sources.map(source=><article className="source-card" aria-disabled="true" key={source.type}><span className="tag">Fictional demonstration source</span><h3>{source.type}</h3><p>{source.detail}</p><dl><div><dt>First detected</dt><dd>{source.first}</dd></div><div><dt>Last checked</dt><dd>{source.checked}</dd></div></dl><button disabled>Source unavailable in demo</button></article>)}</div></div></section>
    <section className="tint"><div className="container grid2"><div><p className="eyebrow"><span/> Agency relevance</p><h2>Best matching proof</h2><p className="lead">The brief connects the opportunity to experience the agency can credibly reference.</p></div><div className="card proof-card"><span className="tag">Fictional demonstration data</span><h3>Financial-services client</h3><p>Three senior data placements · Similar team expansion · Indonesia</p><b>Why it matches:</b><p>The agency has relevant sector, geography, seniority, and role-family evidence for a useful first conversation.</p></div></div></section>
    <section><div className="container"><p className="eyebrow"><span/> Recommended contact order</p><h2>Stakeholder map</h2><div className="stakeholder-intro"><strong>Start with the Head of Talent Acquisition.</strong><p>This role is the most suitable entry point because it can clarify both internal recruiting capacity and whether specialist external agencies are already used.</p></div><div className="grid2">{stakeholders.map(person=><article className="card stakeholder" key={person.role}><span className="contact-order">{person.order.toString().padStart(2,"0")}</span><h3>{person.role}</h3><p>{person.reason}</p><b>Conversation objective</b><p>{person.objective}</p></article>)}</div></div></section>
    <section className="tint"><div className="container uncertainty-grid"><article className="card"><span className="tag">Why Lancara may be wrong</span><h3>The hypothesis has limits.</h3><p>The company may already have sufficient internal recruitment capacity, may use an incumbent agency, or may be intentionally hiring slowly.</p></article><article className="card"><span className="tag">What to verify first</span><h3>Start with the unknown.</h3><p>Confirm whether the positions are actively prioritized and whether specialist external support is currently considered.</p></article></div></section>
    <section><div className="container grid2"><div><p className="eyebrow"><span/> Evidence-led personalization</p><h2>Recommended next action</h2><p className="lead">Ask a careful qualification question without claiming the company is struggling or currently wants an agency.</p></div><div className="card outreach-card"><span className="tag">LinkedIn draft</span><p>Hi [Name]—I noticed NusantaraPay added several data roles recently, including two data-engineering positions that have remained open for more than a month. We recently supported a financial-services team hiring for similar specialist roles. Are these positions fully covered by your internal team, or would additional specialist recruitment capacity be useful?</p><div className="actions"><button disabled>Approve</button><button disabled>Edit</button><button disabled>Reject</button><button disabled>Postpone</button></div><p className="muted">Pilot users will use these decisions to improve future qualification.</p></div></div></section>
  </main><Footer/></>;
}
