"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Nav, Footer } from "@/components/site-shell";

const empty={fullName:"",workEmail:"",jobTitle:"",agencyName:"",agencyWebsite:"",country:"Indonesia",primaryMarket:"Indonesia",specializations:[] as string[],typicalEmployerProfile:"",credibleRoles:"",acquisitionChannels:[] as string[],recentAcquisitionSuccess:"",paidPilotReadiness:"Possibly, depending on results",weeklyFeedbackAvailability:"Yes",contactConsent:false,privacyConsent:false,website:""};
const stepNames=["About your agency","Market and capability","Client acquisition","Calibration readiness"];
const specializationOptions=["Technology","Software engineering","Data / AI","Cloud / DevOps","Cybersecurity","Product / digital"];
const acquisitionOptions=["Referrals and existing relationships","Founder or team network","LinkedIn or email outreach","Events, partnerships or communities","Inbound enquiries","Other"];

export default function Apply(){
  const[step,setStep]=useState(1),[data,setData]=useState(empty),[error,setError]=useState(""),[submitting,setSubmitting]=useState(false),router=useRouter();
  useEffect(()=>{const saved=localStorage.getItem("pilot-application");if(saved){try{setData({...empty,...JSON.parse(saved)})}catch{}}},[]);
  useEffect(()=>{localStorage.setItem("pilot-application",JSON.stringify(data))},[data]);
  const set=(key:string,value:unknown)=>setData(current=>({...current,[key]:value}));
  function toggle(key:"specializations"|"acquisitionChannels",value:string,checked:boolean){set(key,checked?[...data[key],value]:data[key].filter(item=>item!==value))}
  function validate(currentStep:number){
    if(currentStep===1){if([data.fullName,data.workEmail,data.jobTitle,data.agencyName,data.agencyWebsite].some(v=>!v.trim()))return"Please complete every field in About your agency.";if(!/^\S+@\S+\.\S+$/.test(data.workEmail))return"Enter a valid work email address.";try{new URL(/^https?:\/\//i.test(data.agencyWebsite)?data.agencyWebsite:`https://${data.agencyWebsite}`)}catch{return"Enter a valid agency website, such as agency.com."}}
    if(currentStep===2){if(!data.specializations.length)return"Select at least one recruitment specialization.";if(data.typicalEmployerProfile.trim().length<10)return"Describe your typical employer client in at least 10 characters.";if(data.credibleRoles.trim().length<5)return"Tell us which roles your agency fills most credibly."}
    if(currentStep===3&&!data.acquisitionChannels.length)return"Select at least one current client-acquisition method.";
    if(currentStep===4&&(!data.paidPilotReadiness||!data.weeklyFeedbackAvailability))return"Please answer both readiness questions.";if(currentStep===4&&(!data.contactConsent||!data.privacyConsent))return"Please confirm both consent statements before submitting.";
    return"";
  }
  function next(){const message=validate(step);if(message)return setError(message);setError("");setStep(value=>value+1);window.scrollTo({top:0,behavior:"smooth"})}
  async function submit(){const message=validate(4);if(message)return setError(message);setError("");setSubmitting(true);const params=new URLSearchParams(location.search);const utm=Object.fromEntries(["utm_source","utm_medium","utm_campaign","utm_content","utm_term"].map(key=>[key,params.get(key)]).filter(([,value])=>value));const agencyWebsite=/^https?:\/\//i.test(data.agencyWebsite)?data.agencyWebsite:`https://${data.agencyWebsite}`;try{const response=await fetch("/api/applications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...data,agencyWebsite,utm})});if(response.ok){localStorage.removeItem("pilot-application");router.push("/thank-you");return}const body=await response.json();const detail=Array.isArray(body.details)&&body.details[0]?.message?` ${body.details[0].message}`:"";setError(`${body.error||"We could not submit your application."}${detail}`)}catch{setError("We could not reach the application service. Please check your connection and try again.")}finally{setSubmitting(false)}}
  return <><Nav/><main><section><div className="container form"><div className="eyebrow">Free Opportunity Calibration</div><h1>Can Lancara understand your agency’s market?</h1><p className="lead">Tell us enough to assess fit. Detailed ICP configuration, exclusions, account lists, and case studies are collected only after selection.</p><p className="form-note"><strong>Takes approximately 5 minutes.</strong> No payment details, client lists, CRM exports, or candidate information required.</p><ol className="form-steps" aria-label="Application steps">{stepNames.map((name,index)=><li className={index+1===step?"current":index+1<step?"done":""} key={name}><span>{index+1}</span>{name}</li>)}</ol><div className="progress" aria-hidden="true">{[1,2,3,4].map(value=><span className={value<=step?"on":""} key={value}/>)}</div>
    <form onSubmit={event=>{event.preventDefault();if(step<4)next();else submit()}} noValidate>
      {step===1&&<><h2>About your agency</h2>{[["fullName","Your name"],["workEmail","Work email"],["jobTitle","Your role"],["agencyName","Agency name"],["agencyWebsite","Agency website"]].map(([key,label])=><div className="field" key={key}><label htmlFor={key}>{label}</label><input id={key} type={key==="workEmail"?"email":key==="agencyWebsite"?"url":"text"} value={(data as any)[key]} onChange={event=>set(key,event.target.value)} required/></div>)}<div className="honeypot" aria-hidden="true"><label htmlFor="website">Leave this field empty</label><input id="website" name="website" value={data.website} onChange={event=>set("website",event.target.value)} tabIndex={-1} autoComplete="off"/></div></>}
      {step===2&&<><h2>Market and capability</h2><fieldset className="field checkbox-group"><legend>Recruitment specialization</legend>{specializationOptions.map(option=><label key={option}><input type="checkbox" checked={data.specializations.includes(option)} onChange={event=>toggle("specializations",option,event.target.checked)}/>{option}</label>)}</fieldset><div className="field"><label htmlFor="typicalEmployerProfile">Describe your typical employer client</label><textarea id="typicalEmployerProfile" rows={4} placeholder="For example: Indonesian financial-services companies with 200–2,000 employees." value={data.typicalEmployerProfile} onChange={event=>set("typicalEmployerProfile",event.target.value)}/></div><div className="field"><label htmlFor="credibleRoles">Which roles can your agency fill most credibly?</label><textarea id="credibleRoles" rows={4} placeholder="Role families, seniority levels, or specialist skills." value={data.credibleRoles} onChange={event=>set("credibleRoles",event.target.value)}/></div></>}
      {step===3&&<><h2>Client acquisition</h2><fieldset className="field checkbox-group"><legend>How do you usually acquire employer clients?</legend>{acquisitionOptions.map(option=><label key={option}><input type="checkbox" checked={data.acquisitionChannels.includes(option)} onChange={event=>toggle("acquisitionChannels",option,event.target.checked)}/>{option}</label>)}</fieldset><div className="field"><label htmlFor="recentAcquisitionSuccess">Briefly describe what worked most recently <span className="muted">(optional)</span></label><textarea id="recentAcquisitionSuccess" rows={5} placeholder="Describe the approach—not the client’s identity or confidential information." value={data.recentAcquisitionSuccess} onChange={event=>set("recentAcquisitionSuccess",event.target.value)}/></div></>}
      {step===4&&<><h2>Calibration readiness</h2><div className="field"><label htmlFor="paidPilotReadiness">If the three briefs are relevant, can your team approve a Rp4 million four-week pilot?</label><select id="paidPilotReadiness" value={data.paidPilotReadiness} onChange={event=>set("paidPilotReadiness",event.target.value)}>{["Yes","Possibly, depending on results","Not currently"].map(option=><option key={option}>{option}</option>)}</select></div><div className="field"><label htmlFor="weeklyFeedbackAvailability">Can someone review opportunities for 20–30 minutes each week?</label><select id="weeklyFeedbackAvailability" value={data.weeklyFeedbackAvailability} onChange={event=>set("weeklyFeedbackAvailability",event.target.value)}>{["Yes","Possibly","No"].map(option=><option key={option}>{option}</option>)}</select></div><label className="consent"><input type="checkbox" checked={data.contactConsent} onChange={event=>set("contactConsent",event.target.checked)}/>I agree to be contacted about the free calibration and founding pilot.</label><label className="consent"><input type="checkbox" checked={data.privacyConsent} onChange={event=>set("privacyConsent",event.target.checked)}/>I have read the privacy notice and understand that applying does not guarantee selection.</label></>}
      {error&&<p role="alert" className="warning">{error}</p>}<div className="actions">{step>1&&<button type="button" className="button secondary" onClick={()=>{setError("");setStep(value=>value-1)}}>Back</button>}<button className="button" type="submit" disabled={submitting}>{step<4?"Continue":submitting?"Submitting…":"Apply for calibration"}</button></div>
    </form>
  </div></section></main><Footer/></>}
