import Link from "next/link";
import { Nav,Footer } from "@/components/site-shell";
import { Reveal } from "@/components/reveal";
import { siteConfig } from "@/lib/config";

const outcomes=[{n:"01",title:"Find demand earlier",copy:"Identify companies showing credible evidence of active or difficult technology hiring."},{n:"02",title:"Research less",copy:"Replace repetitive account research with a reviewed, customer-specific shortlist."},{n:"03",title:"Approach with context",copy:"Give your team an evidence-backed reason to begin a relationship-oriented conversation."}];
export default function Home(){return <><Reveal/><Nav/><main>
  <section className="home-hero container">
    <div className="hero-copy reveal"><p className="eyebrow"><span/> Founding pilot for recruitment agencies</p><h1>Find companies that may need recruitment support <em>before competitors do.</em></h1><p className="hero-lede">Research-backed accounts showing credible demand for difficult-to-fill technology talent—complete with hiring evidence, stakeholder roles, and human-reviewed outreach angles.</p><div className="hero-actions"><Link className="button button-lime" href="/apply">Apply for the founding pilot <span>↗</span></Link><Link className="text-link" href="/sample-opportunity"><span className="play">▶</span> View a sample opportunity</Link></div><div className="social-proof"><div className="signal-stack" aria-hidden="true"><span>HI</span><span>TA</span><span>VP</span></div><p><strong>AI-assisted research. Human-reviewed recommendations.</strong><br/>No automated outreach.</p></div></div>
    <div className="hero-visual reveal delay-1" aria-label="Sample opportunity intelligence dashboard"><div className="orb orb-one"/><div className="orb orb-two"/><div className="dashboard-card"><div className="dash-top"><div><small>FICTIONAL OPPORTUNITY</small><strong>NusantaraPay</strong></div><span className="live-pill">● Contact now</span></div><div className="impact-number"><span>Opportunity score</span><strong>84<span>/100</span></strong></div><div className="progress"><span/></div><div className="dash-labels"><span>Fit</span><span>Evidence</span><span>Timing</span></div></div><div className="floating-card signal-card"><span className="mini-label">RELEVANT SIGNAL</span><strong>7 technology vacancies</strong><p>Four first observed in the past 14 days.</p></div><div className="floating-card confidence-card"><span>CONFIDENCE</span><strong>HIGH</strong><i>↗</i></div></div>
  </section>
  <section className="trust-strip container reveal"><p>Opportunity intelligence built for relationship-led sales</p><div><span>EVIDENCE FIRST</span><b>✦</b><span>HUMAN REVIEWED</span><b>✦</b><span>NO AUTO OUTREACH</span></div></section>
  <section className="intro section container" id="problem"><div className="section-label reveal"><span>01</span> Why this exists</div><div className="intro-grid"><div className="reveal"><p className="eyebrow"><span/> Timing. Context. Focus.</p><h2>Account research is slow. <em>Timing is hard to see.</em></h2></div><div className="intro-copy reveal delay-1"><p>Recruitment agencies win through relationships. The challenge is deciding which companies deserve attention now—and approaching them with credible context instead of another generic message.</p><Link className="arrow-link" href="/#how">See the research workflow <span>↗</span></Link></div></div><div className="stat-grid reveal"><article><span>THE SIGNAL</span><strong>7</strong><p>relevant technology vacancies in the sample</p></article><article className="featured"><span>OPPORTUNITY SCORE</span><strong>84</strong><p>explainable points out of 100</p></article><article><span>THE SHORTLIST</span><strong>1×</strong><p>focused delivery each week</p></article><article><span>THE OUTREACH</span><strong>0</strong><p>messages sent automatically</p></article></div></section>
  <section className="process section" id="how"><div className="container"><div className="process-heading reveal"><div><p className="eyebrow light"><span/> How it works</p><h2>We configure, research,<br/>and <em>refine.</em></h2></div><p>A focused service that turns public hiring evidence into a reviewed commercial hypothesis—without replacing your judgment or relationships.</p></div><div className="process-steps">{[{n:"01",icon:"◎",title:"Define your market",copy:"Tell us your specialization, preferred clients, geography, and commercial fit.",status:"Customer-specific ICP"},{n:"02",icon:"⌁",title:"Review the signals",copy:"We monitor relevant companies and qualify dated hiring evidence against your rules.",status:"Human-reviewed research",active:true},{n:"03",icon:"↗",title:"Start with context",copy:"Receive opportunity briefs, stakeholder roles, and a careful outreach angle.",status:"Feedback improves fit"}].map(x=><article className={`process-step reveal ${x.active?"active":""}`} key={x.n}><div className="step-no">{x.n}</div><div className="step-icon">{x.icon}</div><p className="step-date">WEEKLY WORKFLOW</p><h3>{x.title}</h3><p>{x.copy}</p><span className="step-status">{x.status}</span></article>)}</div></div></section>
  <section className="section container"><div className="opportunity-card reveal"><div className="opportunity-copy"><p className="eyebrow"><span/> Fictional demonstration</p><h2>Meet the<br/><em>NusantaraPay brief.</em></h2><p>See exactly how dated evidence, stakeholder roles, confidence, and an explicit opportunity hypothesis come together.</p><Link className="button button-dark" href="/sample-opportunity">Explore the full sample <span>↗</span></Link></div><div className="outcome-grid">{outcomes.map(x=><article key={x.n}><span>{x.n}</span><i>◇</i><h3>{x.title}</h3><p>{x.copy}</p></article>)}</div></div></section>
  <section className="section container" id="pilot"><div className="pilot-heading reveal"><div><p className="eyebrow"><span/> Founding pilot</p><h2>Help shape a service<br/><em>your team would use.</em></h2></div><p>Selected agencies receive customer-specific configuration, verified opportunities, hiring evidence, stakeholder roles, and direct influence on the product.</p></div><div className="pilot-grid reveal"><article><span>01</span><i>◎</i><h3>Share your ICP</h3><p>Define specializations, markets, roles, and account preferences.</p></article><article><span>02</span><i>◇</i><h3>Review real briefs</h3><p>Assess three manually prepared opportunities against your workflow.</p></article><article className="highlight"><span>03</span><i>↗</i><h3>Shape the pilot</h3><p>Refine the qualification rules and consider a paid concierge engagement.</p><Link href="/apply">Apply now ↗</Link></article></div><p className="capacity-note reveal">Planned capacity: {siteConfig.pilotCapacity} agencies. Limited by manual review—not artificial urgency.</p></section>
</main><Footer/></>}
