import Link from "next/link";
import { Nav, Footer } from "@/components/site-shell";
import { Reveal } from "@/components/reveal";
import { siteConfig } from "@/lib/config";

const signalLevels=[
  ["One relevant vacancy","Monitor"],
  ["Several related specialist vacancies","Possible demand"],
  ["Repeated or long-open specialist roles","Potential hiring bottleneck"],
  ["Hiring spike plus expansion or funding","Stronger timing"],
  ["Signals plus agency-specialization match","Prioritized opportunity"],
];
const timeline=[
  ["Day 1","Configure the playbook","Define specialization, industries, roles, geography, commercial requirements, exclusions, and relevant agency proof."],
  ["Days 2–4","Research and qualify","Lancara maps relevant accounts, combines signals, verifies evidence, and prepares three briefs."],
  ["Day 5","Review the opportunities","Approve, edit, reject, or postpone each recommendation and explain what should improve."],
  ["After calibration","Begin the paid pilot","Receive a calibrated weekly research funnel for four weeks, with weekly refinement."],
];
const evaluation=["Opportunities approved as relevant","Approved accounts actually contacted","Research time saved","Replies, conversations, and meetings","Reasons opportunities were rejected","Signals associated with accepted opportunities","Relevance improvement over four weeks"];

export default function Home(){return <><Reveal/><Nav/><main>
  <section className="home-hero container">
    <div className="hero-copy reveal"><p className="eyebrow"><span/> Free Opportunity Calibration</p><h1>Know which companies to approach this week—<em>and why now.</em></h1><p className="hero-lede">Lancara runs a customer-specific Hiring Demand Playbook for technology recruitment agencies. We combine vacancy patterns, hiring friction, company events, and your agency’s strengths into human-reviewed opportunity briefs.</p><p className="qualification-line">Selected agencies receive their first three calibrated opportunities within five business days after configuration and complete inputs.</p><div className="hero-actions"><Link className="button button-lime" href="/apply">Apply for a free calibration <span>↗</span></Link><Link className="text-link" href="/sample-opportunity"><span className="play">▶</span> View a sample opportunity</Link></div><div className="social-proof"><div className="signal-stack" aria-hidden="true"><span>HI</span><span>TA</span><span>VP</span></div><p><strong>AI-assisted research. Human-reviewed recommendations.</strong><br/>No automated outreach.</p></div></div>
    <div className="hero-visual reveal delay-1" aria-label="Sample opportunity intelligence dashboard"><div className="orb orb-one"/><div className="orb orb-two"/><div className="dashboard-card"><div className="dash-top"><div><small>FICTIONAL OPPORTUNITY</small><strong>NusantaraPay</strong></div><span className="live-pill">● Contact now</span></div><div className="impact-number"><span>Opportunity score</span><strong>84<span>/100</span></strong></div><div className="progress"><span/></div><div className="dash-labels"><span>Fit</span><span>Demand</span><span>Timing</span></div></div><div className="floating-card signal-card"><span className="mini-label">SIGNAL STACK</span><strong>Specialist hiring bottleneck</strong><p>Multiple related roles plus persistent postings.</p></div><div className="floating-card confidence-card"><span>CONFIDENCE</span><strong>HIGH</strong><i>↗</i></div></div>
  </section>

  <section className="trust-strip container reveal"><p>Opportunity intelligence built for relationship-led sales</p><div><span>EVIDENCE FIRST</span><b>✦</b><span>HUMAN REVIEWED</span><b>✦</b><span>NO AUTO OUTREACH</span></div></section>

  <section className="section container signal-section" id="signals"><div className="section-label reveal"><span>01</span> Signal stacking</div><div className="intro-grid"><div className="reveal"><p className="eyebrow"><span/> More than job alerts</p><h2>We do not count vacancies. <em>We combine signals.</em></h2></div><div className="intro-copy reveal delay-1"><p><strong>The Lancara Hiring Demand Playbook</strong> is a customer-specific research workflow that continuously identifies, qualifies, and explains companies showing credible specialist hiring demand.</p><p>A signal supports a commercial hypothesis. It is never presented as proof that a company will buy.</p></div></div><div className="signal-ladder reveal">{signalLevels.map(([evidence,interpretation],index)=><article key={evidence}><span>{String(index+1).padStart(2,"0")}</span><p>{evidence}</p><strong>{interpretation}</strong></article>)}</div></section>

  <section className="section container"><div className="opportunity-card reveal"><div className="opportunity-copy"><p className="eyebrow"><span/> See the output first</p><h2>Meet the<br/><em>NusantaraPay brief.</em></h2><p>Inspect the signal stack, evidence, uncertainty, stakeholder order, agency match, and careful conversation angle.</p><Link className="button button-dark" href="/sample-opportunity">Explore the full sample <span>↗</span></Link></div><div className="sample-proof"><span>FICTIONAL DEMONSTRATION</span><strong>84<small>/100</small></strong><h3>Specialist hiring bottleneck</h3><ul><li>Seven technology vacancies</li><li>Two persistent data roles</li><li>Recent expansion context</li><li>Strong agency capability match</li></ul></div></div></section>

  <section className="process section" id="how"><div className="container"><div className="process-heading reveal"><div><p className="eyebrow light"><span/> Your first five business days</p><h2>From configuration<br/>to <em>useful evidence.</em></h2></div><p>The five-day delivery window begins after the configuration call and receipt of the information required to configure your playbook.</p></div><div className="timeline-grid">{timeline.map(([date,title,copy],index)=><article className={`timeline-card reveal ${index===2?"active":""}`} key={date}><span>{date}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>

  <section className="section container offer-section" id="pilot"><div className="offer-heading reveal"><p className="eyebrow"><span/> Clear commercial stages</p><h2>Prove relevance for free.<br/><em>Then test the workflow.</em></h2></div><div className="offer-grid reveal">
    <article><span className="tag">Stage 1 · No payment</span><h3>Free Opportunity Calibration</h3><p>Determine whether Lancara can understand your agency’s market.</p><ul><li>One 30-minute configuration session</li><li>One customer-specific Hiring Demand Playbook</li><li>Three manually researched opportunity briefs</li><li>Evidence, signal stack, and stakeholder roles</li><li>One 20-minute review session</li><li>Delivered within five business days after complete inputs</li></ul><Link className="button button-dark" href="/apply">Apply for calibration <span>↗</span></Link><small>Limited to selected agencies. Five staggered calibrations in the initial cycle.</small></article>
    <article className="paid-offer"><span className="tag">Stage 2 · Paid</span><h3>Four-Week Founding Pilot</h3><div className="price">Rp4 million <small>paid before the pilot begins</small></div><ul><li>One configured Hiring Demand Playbook</li><li>10–15 potentially relevant accounts researched weekly</li><li>5–8 complete human-reviewed briefs weekly</li><li>Stakeholder roles and conversation angles</li><li>One 30-minute calibration session weekly</li><li>Weekly relevance and activity summary</li><li>Up to two participating team members</li></ul><strong className="availability">Offered after successful calibration</strong><small>Maximum two paid pilots running simultaneously.</small></article>
  </div></section>

  <section className="section principles"><div className="container principles-grid"><div className="reveal"><p className="eyebrow light"><span/> Human control</p><h2>Useful hypotheses,<br/><em>not fabricated certainty.</em></h2><p>Every brief separates facts from inference, states evidence confidence, explains what may be wrong, and recommends what the salesperson should verify first.</p></div><div className="principle-list reveal delay-1"><article><span>01</span><h3>Evidence before recommendation</h3><p>Dated sources remain visible and uncertainty is explicit.</p></article><article><span>02</span><h3>Your agency changes the answer</h3><p>Accounts are evaluated against your capabilities, proof, and commercial focus.</p></article><article><span>03</span><h3>Feedback refines the playbook</h3><p>Approve, edit, reject, or postpone recommendations each week.</p></article></div></div></section>

  <section className="section container measurement-section"><div className="intro-grid"><div className="reveal"><p className="eyebrow"><span/> How we evaluate the pilot</p><h2>Measured by relevance<br/>and <em>real sales usage.</em></h2><p className="lead">We do not judge the pilot by the size of a lead list.</p></div><div className="measurement-list reveal delay-1">{evaluation.map((item,index)=><div key={item}><span>{String(index+1).padStart(2,"0")}</span><p>{item}</p></div>)}</div></div></section>

  <section className="section scope-section"><div className="container"><div className="section-label"><span>Scope</span> What the founding pilot does not include</div><div className="scope-grid"><article><span>×</span><p>No automated or bulk outreach</p></article><article><span>×</span><p>No LinkedIn scraping or candidate personal data</p></article><article><span>×</span><p>No guaranteed meetings or placement outcomes</p></article><article><span>×</span><p>No CRM implementation or unlimited markets</p></article></div></div></section>

  <section className="operator-section section"><div className="container operator-card reveal"><div><p className="eyebrow"><span/> Built by Lancara in Indonesia</p><h2>Opportunity intelligence for relationship-led recruitment sales.</h2></div><div><p>Built by <strong>Daffa Arazaan</strong>. We are developing opportunity intelligence specifically for relationship-led recruitment sales in Indonesia.</p><div className="operator-links"><a className="arrow-link" href={siteConfig.linkedIn} target="_blank" rel="noreferrer">View LinkedIn <span>↗</span></a><a className="arrow-link" href={`mailto:${siteConfig.email}`}>Contact Daffa <span>↗</span></a></div></div></div></section>

  <section className="section container faq-section"><div className="section-label"><span>FAQ</span> Before you apply</div><div className="faq-grid"><details><summary>Is this a contact database?</summary><p>No. Lancara for Recruitment is a configured research workflow, not a bulk contact list.</p></details><details><summary>What happens after I apply?</summary><p>Lancara manually reviews fit. Selected agencies are invited to a 30-minute configuration session before the five-business-day delivery period begins.</p></details><details><summary>What is free and what becomes paid?</summary><p>The first three calibrated briefs and review session are free. A four-week pilot is offered only after successful calibration and costs Rp4 million upfront.</p></details><details><summary>Which sources are monitored?</summary><p>Official careers pages, public job boards, company announcements, reputable public reporting, and selected customer-provided accounts after onboarding.</p></details><details><summary>Do you scrape LinkedIn?</summary><p>No. The founding pilot does not depend on LinkedIn scraping or automated outreach.</p></details><details><summary>Is a hiring signal proof that a company will buy?</summary><p>No. It supports a commercial hypothesis. Each brief explains its evidence, uncertainty, and what should be verified first.</p></details><details><summary>How much time does weekly review require?</summary><p>Plan for approximately 20–30 minutes each week during the paid pilot.</p></details></div></section>

  <section className="final-cta section"><div className="container"><p className="eyebrow light"><span/> Initial validation cycle</p><h2>Calibrate a playbook<br/>around <em>your market.</em></h2><p>Five selected agencies. Three human-reviewed opportunities. No payment required.</p><Link className="button button-lime" href="/apply">Apply for a free calibration <span>↗</span></Link></div></section>
</main><Footer/></>}
