export const siteConfig = {
  company: "Lancara",
  name: "Lancara",
  logoText: "Lancara",
  program: "Lancara Founding Pilot",
  headline: "Know which companies deserve your attention — and why now.",
  email: "daffaulayafaros@gmail.com",
  bookingUrl: process.env.NEXT_PUBLIC_BOOKING_URL || "",
  pilotCapacity: "2",
  operator: "Lancara",
  operatorContact: "Daffa Arazaan",
  jurisdiction: "Indonesia",
  linkedIn: "https://www.linkedin.com/in/daffa-arazaan",
  accent: "#c8f06a",
};
