create extension if not exists pgcrypto;
create table if not exists public.pilot_applications (
 id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 full_name text not null, work_email text not null, phone text, job_title text not null, agency_name text not null, agency_website text not null, linkedin_company_url text, country text not null, primary_market text not null,
 recruiter_count_range text not null, sales_count_range text, specializations jsonb not null default '[]', geographic_coverage jsonb not null default '[]', client_company_sizes jsonb not null default '[]', role_categories jsonb not null default '[]', placement_fee_range text, industries_served jsonb not null default '[]', excluded_industries jsonb not null default '[]',
 recent_client_sources text, accounts_researched_last_week integer, weekly_research_hours numeric, current_sources jsonb not null default '[]', last_signal_based_outreach text, biggest_acquisition_problem text not null, research_owner text, current_prioritization_method text,
 willing_to_share_icp text not null, willing_to_share_accounts text not null, willing_to_review_sample text not null, sample_reviewer text, paid_pilot_openness text not null, preferred_call_timing text, additional_notes text,
 contact_consent boolean not null, privacy_consent boolean not null, qualification_score integer not null check(qualification_score between 0 and 100), qualification_band text not null, score_breakdown jsonb not null,
 application_status text not null default 'new', validation_stage text not null default 'application', internal_notes text, assigned_owner text,
 discovery_call_booked boolean not null default false, discovery_call_attended boolean not null default false, icp_received boolean not null default false, target_accounts_received boolean not null default false, sample_delivered boolean not null default false, sample_reviewed boolean not null default false, pilot_offered boolean not null default false, pilot_accepted boolean not null default false, pilot_paid boolean not null default false,
 utm_source text, utm_medium text, utm_campaign text, utm_content text, utm_term text, referrer text
);
create table if not exists public.pilot_application_events(id uuid primary key default gen_random_uuid(),application_id uuid not null references public.pilot_applications(id) on delete cascade,created_at timestamptz not null default now(),event_type text not null,previous_value jsonb,new_value jsonb,notes text,actor text);
create index if not exists pilot_app_created_idx on public.pilot_applications(created_at desc);create index if not exists pilot_app_email_idx on public.pilot_applications(work_email);create index if not exists pilot_app_agency_idx on public.pilot_applications(agency_name);create index if not exists pilot_app_band_idx on public.pilot_applications(qualification_band);create index if not exists pilot_app_status_idx on public.pilot_applications(application_status);create index if not exists pilot_app_stage_idx on public.pilot_applications(validation_stage);
alter table public.pilot_applications enable row level security;alter table public.pilot_application_events enable row level security;
-- No public policies: reads/writes occur only through validated server routes using the service role.
